#!/bin/sh

###################
# PBS settings #
###################

#PBS -N fast_5subst
#PBS -l nodes=1:ppn=24
#PBS -l walltime=06:00:00
#PBS -q gpu
#PBS -j oe
#PBS -o pbs.out

###################
# script settings #
###################

TARGET_ATTENTION='all_layers'
DATASET="PF00533" 
MAX_TOKENS=None
LOSS_METHOD="max_tokens_repr"
N_SEQUENCES=100
MIN_FILTER=100
DEVICE="cuda"
LOAD=False

###########
# modules #
###########

module load conda/4.9.2
conda activate esm 

###############
# directories #
###############

WORKING_DIR="/u/external/gcarbone/adversarial-protein-sequences/src"
OUT_DIR="/fast/external/gcarbone/adversarial-protein-sequences_out/"
DATA_DIR="/scratch/external/gcarbone/msa/hhfiltered/"
	
cd $WORKING_DIR
PBS_O_WORKDIR=$(pwd)
LOGS_DIR="${OUT_DIR}logs/"
mkdir -p $LOGS_DIR
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M:%S)
OUT="${LOGS_DIR}${DATE}_${TIME}_out.txt"

#######
# run #
#######

for TOKEN_SELECTION in 'max_attention'; do # 'min_entropy' 'max_entropy'

	for N_SUBSTITUTIONS in 5; do

		python attack_msa.py --data_dir=$DATA_DIR --out_dir=$OUT_DIR --loss_method=$LOSS_METHOD \
			--dataset=$DATASET --max_tokens=$MAX_TOKENS --token_selection=$TOKEN_SELECTION \
			--n_sequences=$N_SEQUENCES --n_substitutions=$N_SUBSTITUTIONS --device=$DEVICE --load=$LOAD \
			--target_attention=$TARGET_ATTENTION --min_filter=$MIN_FILTER >> $OUT 2>&1

	done
done

conda deactivate

