#!/bin/sh

###################
# PBS settings #
###################

#PBS -N single_seq_attack
#PBS -l nodes=1:ppn=12
#PBS -l walltime=5:00:00
#PBS -q gpu
#PBS -j oe
#PBS -o pbs.out

###################
# script settings #
###################

DATASET="PF00533" 
MAX_TOKENS=None
N_SEQUENCES=30
MIN_FILTER=100
TOKEN_SELECTION="max_attention" # 'min_entropy' 'max_entropy'
TARGET_ATTENTION='all_layers' # 'all_layers' 'last_layer'
LOSS_METHOD="max_masked_prob"
N_SUBSTITUTIONS=3
DEVICE="cuda"
LOAD=False

###########
# modules #
###########

eval "$(conda shell.bash hook)"
# module load conda/4.9.2
conda activate esm

###############
# directories #
###############

WORKING_DIR="/u/external/gcarbone/adversarial-protein-sequences/src"
OUT_DIR="/fast/external/gcarbone/adversarial-protein-sequences_out/"
DATA_DIR="/scratch/external/gcarbone/msa/hhfiltered/" # "/scratch/external/gcarbone/pfam/"

cd $WORKING_DIR
PBS_O_WORKDIR=$(pwd)
LOGS_DIR="${OUT_DIR}logs/"
mkdir -p $LOGS_DIR
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M:%S)
OUT="${LOGS_DIR}${DATE}_${TIME}_out.txt"

#######
# run #
#######


python attack_single_sequences.py --data_dir=$DATA_DIR --out_dir=$OUT_DIR \
	--dataset=$DATASET --max_tokens=$MAX_TOKENS \
	--n_sequences=$N_SEQUENCES --n_substitutions=$N_SUBSTITUTIONS --device=$DEVICE --load=$LOAD \
	--target_attention=$TARGET_ATTENTION >> $OUT 2>&1

conda deactivate

