#!/bin/sh

###################
# PBS settings #
###################

#PBS -N single_seq_pfam
#PBS -l nodes=1:ppn=24
#PBS -l walltime=40:00:00
#PBS -q gpu
#PBS -j oe
#PBS -o pbs.out

###################
# script settings #
###################

TARGET_ATTENTION='last_layer' # last_layer, all_layers
MAX_TOKENS=200
N_SEQUENCES=100
DEVICE="cuda"
LOAD=False

###########
# modules #
###########

module load conda/4.9.2
conda activate esm

###############
# directories #
###############

WORKING_DIR="/u/external/gcarbone/adversarial-protein-sequences/src"
OUT_DIR="/fast/external/gcarbone/adversarial-protein-sequences_out/"
DATA_DIR="/scratch/external/gcarbone/pfam/"

cd $WORKING_DIR
PBS_O_WORKDIR=$(pwd)
LOGS_DIR="${OUT_DIR}logs/"
mkdir -p $LOGS_DIR
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M:%S)
OUT="${LOGS_DIR}${DATE}_${TIME}_out.txt"

#######
# run #
#######

for DATASET in "fastaPF00001", "fastaPF00004"
do

	for N_SUBSTITUTIONS in 3 10
	do
		python attack_single_sequences.py --data_dir=$DATA_DIR --out_dir=$OUT_DIR \
			--dataset=$DATASET --max_tokens=$MAX_TOKENS \
			--n_sequences=$N_SEQUENCES --n_substitutions=$N_SUBSTITUTIONS --device=$DEVICE --load=$LOAD \
			--target_attention=$TARGET_ATTENTION >> $OUT 2>&1

	done
done

conda deactivate

