#!/bin/sh

################
# PBS settings #
################

#PBS -N ProTherm_attack
#PBS -l nodes=1:ppn=24
#PBS -l walltime=10:00:00
#PBS -q fat
#PBS -j oe
#PBS -o pbs.out

###################
# script settings #
###################

MAX_TOKENS=None
MIN_FILTER=50
N_SUBSTITUTIONS=10
MODEL="ESM_MSA" # "ESM", "ESM_MSA"
TOKEN_SELECTION="max_attention" # 'min_entropy' 'max_entropy'
TARGET_ATTENTION='last_layer' # 'all_layers' 'last_layer'
LOSS_METHOD="max_masked_prob"
DEVICE="cpu"
LOAD=False

###########
# modules #
###########

eval "$(conda shell.bash hook)"
conda activate esm 

###############
# directories #
###############

WORKING_DIR="/u/external/gcarbone/adversarial-protein-sequences/src"
OUT_DIR="/fast/external/gcarbone/adversarial-protein-sequences_out/"
DATA_DIR="/scratch/external/gcarbone/"
	
cd $WORKING_DIR
PBS_O_WORKDIR=$(pwd)
LOGS_DIR="${OUT_DIR}logs/"
mkdir -p $LOGS_DIR
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M:%S)
OUT="${LOGS_DIR}${DATE}_${TIME}_out.txt"

#######
# run #
#######

python attack_msa.py --data_dir=$DATA_DIR --out_dir=$OUT_DIR --model=$MODEL --loss_method=$LOSS_METHOD \
	--dataset=$DATASET --max_tokens=$MAX_TOKENS --token_selection=$TOKEN_SELECTION \
	--n_substitutions=$N_SUBSTITUTIONS --device=$DEVICE --load=$LOAD \
	--target_attention=$TARGET_ATTENTION --min_filter=$MIN_FILTER >> $OUT 2>&1

conda deactivate

