#!/bin/sh

###################
# PBS settings #
###################

#PBS -S /bin/bash
#PBS -N hhfilter
#PBS -l nodes=1:ppn=12
#PBS -l walltime=10:00:00
#PBS -q gpu
#PBS -j oe
#PBS -o pbs.out

###########
# modules #
###########

eval "$(conda shell.bash hook)"
conda activate esm 

###############
# directories #
###############

WORKING_DIR="/u/external/gcarbone/adversarial-protein-sequences/preprocess/"
OUT_DIR="/fast/external/gcarbone/adversarial-protein-sequences_out/"
	
cd $WORKING_DIR
PBS_O_WORKDIR=$(pwd)
LOGS_DIR="${OUT_DIR}logs/"
mkdir -p $LOGS_DIR
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M:%S)
OUT="${LOGS_DIR}${DATE}_${TIME}_out.txt"

./hhfilter_protherm.sh > $OUT 2>&1


