#!/bin/sh

###################
# PBS settings #
###################

#PBS -N predict_structures
#PBS -l nodes=1:ppn=12
#PBS -l walltime=20:00:00
#PBS -q gpu
#PBS -j oe
#PBS -o pbs.out

###################
# script settings #
###################

DATASET="PF00627" # PF00533, PF00627, PF00240
MAX_TOKENS=None
N_SEQUENCES=100
MIN_FILTER=100
TOKEN_SELECTION='max_attention' # 'max_attention', 'min_entropy' 'max_entropy'
TARGET_ATTENTION='last_layer' # 'all_layers' 'last_layer'
LOSS_METHOD='max_masked_prob' # 'target_probs' 'tokens_repr' 'max_masked_prob'
N_SUBSTITUTIONS=3
PLDDT_THS=80
LOAD=False

###########
# modules #
###########

eval "$(conda shell.bash hook)"
conda activate /u/external/gcarbone/colabfold_batch/colabfold-conda/
module load cuda/11.0.3

###############
# directories #
###############

WORKING_DIR="/u/external/gcarbone/adversarial-protein-sequences/src"
OUT_DIR="/fast/external/gcarbone/adversarial-protein-sequences_out/"
DATA_DIR="${OUT_DIR}msa/"
	
cd $WORKING_DIR
PBS_O_WORKDIR=$(pwd)
LOGS_DIR="${OUT_DIR}logs/"
mkdir -p $LOGS_DIR
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M:%S)
OUT="${LOGS_DIR}${DATE}_${TIME}_out.txt"

#######
# run #
#######

for ((min=0; min<=$N_SEQUENCES; min+=1)); do

	python predict_structures_fast.py --min=$min --max=$min --data_dir=$DATA_DIR --out_dir=$OUT_DIR --load=$LOAD \
		--dataset=$DATASET --n_sequences=$N_SEQUENCES --min_filter=$MIN_FILTER  --loss_method=$LOSS_METHOD \
		--max_tokens=$MAX_TOKENS --token_selection=$TOKEN_SELECTION --n_substitutions=$N_SUBSTITUTIONS \
		--target_attention=$TARGET_ATTENTION --plddt_ths=60 --plot=False >> $OUT 2>&1

	python predict_structures_fast.py --min=0 --max=$min --data_dir=$DATA_DIR --out_dir=$OUT_DIR --load=True \
		--dataset=$DATASET --n_sequences=$N_SEQUENCES --min_filter=$MIN_FILTER  --loss_method=$LOSS_METHOD \
		--max_tokens=$MAX_TOKENS --token_selection=$TOKEN_SELECTION --n_substitutions=$N_SUBSTITUTIONS \
		--target_attention=$TARGET_ATTENTION --plddt_ths=$PLDDT_THS --plot=True >> $OUT 2>&1

done

conda deactivate
