#!/bin/sh

###################
# PBS settings #
###################

#PBS -N msa_atk_500
#PBS -l nodes=1:ppn=20
#PBS -l walltime=10:00:00
#PBS -q fat
#PBS -j oe
#PBS -o pbs.out

###################
# script settings #
###################

TARGET_ATTENTION='last_layer' # last_layer, all_layers
ALIGN=True
MAX_TOKENS=500
N_SEQUENCES=500
DEVICE="cpu"
LOAD=False

###########
# modules #
###########

module load conda/4.9.2
conda activate esm

###############
# directories #
###############

DATA_DIR="/scratch/external/gcarbone/pfam_fasta/"
WORKING_DIR="storage/adversarial-protein-sequences/src"
DATA_OUT="../out"

cd $WORKING_DIR
PBS_O_WORKDIR=$(pwd)
LOGS="../out/logs"
mkdir -p $LOGS
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M:%S)
OUT="${LOGS}/${DATE}_${TIME}_out.txt"

#######
# run #
#######

for DATASET in "fastaPF00001" #"fastaPF00004" 
do
	for N_SUBSTITUTIONS in 3 10 20
	do
		python msa_test.py --data_dir=$DATA_DIR --out_dir=$DATA_OUT \
			--dataset=$DATASET --align=$ALIGN --max_tokens=$MAX_TOKENS \
			--n_sequences=$N_SEQUENCES --n_substitutions=$N_SUBSTITUTIONS --device=$DEVICE --load=$LOAD \
			--target_attention=$TARGET_ATTENTION >> $OUT 2>&1

	done
done

conda deactivate

