#!/bin/sh

###################
# PBS settings #
###################

#PBS -N pf1_3subst
#PBS -l nodes=1:ppn=10
#PBS -l walltime=01:00:00
#PBS -q fat
#PBS -j oe
#PBS -o pbs.out

###################
# script settings #
###################

TARGET_ATTENTION='last_layer' # last_layer, all_layers
ALIGN=True
MAX_TOKENS=100
N_SEQUENCES=100
DEVICE="cpu"
LOAD=False

###############
# directories #
###############

WORKING_DIR="storage/adversarial-protein-sequences/src"
LOGS="${WORKING_DIR}/../out/logs"
cd $WORKING_DIR
PBS_O_WORKDIR=$(pwd)

#######
# run #
#######

DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M:%S)
mkdir -p $LOGS
OUT="${LOGS}/${DATE}_${TIME}_out.txt"

module load conda/4.9.2
module load cuda/11.0.3
conda activate conda_venv

for DATASET in "fastaPF00001" #"fastaPF00004" 
do
	for N_SUBSTITUTIONS in 3 #10 20
	do
		python pfam_test.py --dataset=$DATASET --align=$ALIGN --max_tokens=$MAX_TOKENS \
			--n_sequences=$N_SEQUENCES --n_substitutions=$N_SUBSTITUTIONS --device=$DEVICE --load=$LOAD \
			--target_attention=$TARGET_ATTENTION >> $OUT 2>&1

	done
done

conda deactivate

