#!/bin/sh

###################
# PBS settings #
###################

#PBS -N msa_128ham_200seq
#PBS -l nodes=2:ppn=24
#PBS -l walltime=30:00:00
#PBS -q fat
#PBS -j oe
#PBS -o pbs.out

###################
# script settings #
###################

TARGET_ATTENTION='last_layer' # last_layer, all_layers
ALIGN=False
MAX_TOKENS=None
N_SEQUENCES=200
DEVICE="cpu"
LOAD=False
MAX_HAMMING_MSA_SIZE=128

###########
# modules #
###########

module load conda/4.9.2
conda activate esm

###############
# directories #
###############

WORKING_DIR="storage/adversarial-protein-sequences/src"
DATA_DIR="/scratch/external/gcarbone/msa/"
DATASET="PF00533_rp15" 
DATA_OUT="../out"

cd $WORKING_DIR
PBS_O_WORKDIR=$(pwd)
LOGS="../out/logs"
mkdir -p $LOGS
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M:%S)
OUT="${LOGS}/${DATE}_${TIME}_out.txt"

#######
# run #
#######

for N_SUBSTITUTIONS in 3 10 20
do

	python attack_msa.py --data_dir=$DATA_DIR --out_dir=$DATA_OUT \
		--dataset=$DATASET --align=$ALIGN --max_tokens=$MAX_TOKENS \
		--n_sequences=$N_SEQUENCES --n_substitutions=$N_SUBSTITUTIONS --device=$DEVICE --load=$LOAD \
		--target_attention=$TARGET_ATTENTION --max_hamming_msa_size=$MAX_HAMMING_MSA_SIZE >> $OUT 2>&1

done

conda deactivate

